version: '3'
services:
  app:
    build: .
    command: bash -c "bundle exec rake extension"
    container_name: nothub
    volumes:
      - .:/app
      - bundle:/bundle
    environment:
      BUNDLE_PATH: /bundle

volumes:
  bundle:
